function Hd = lpfilter
%LPFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 11-Jan-2019 00:54:13

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 173.61;  % Sampling Frequency

N    = 10;         % Order
Fc   = 40;         % Cutoff Frequency
flag = 'noscale';  % Sampling Flag
Beta = 0.5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
